# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: Build coalwater's keyboard
on:
  push:
    branches:
      - cirque

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["splitkb_aurora_corne_left","splitkb_aurora_corne_right"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      clipboard: '["default"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["#define SPLIT_POINTING_ENABLE\n#define POINTING_DEVICE_RIGHT\n#define POINTING_DEVICE_ROTATION_90\n#define MASTER_RIGHT"]'
      branches: '["caksoylar/zmk/feat/mouse-keys-3.2","zmkfirmware/zmk/main caksoylar/zmk/feat/mouse-keys-3.2"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=7200000\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y\nCONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y\nCONFIG_ZMK_POINTER=y\nCONFIG_ZMK_POINTER_DEVICE=cirque"]'
